version: '3.9'
services:
    minio:
      image: minio/minio
      command: server --console-address :9005 /data
      ports:
        - '9000:9000'
        - '9005:9005'
      environment:
        - MINIO_ROOT_USER=minioadmin
        - MINIO_ROOT_PASSWORD=minioadmin
      restart: always
      volumes:
         - ./minio-data:/data
      healthcheck:
        test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
        interval: 30s
        timeout: 20s
        retries: 3